[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BookDone"
authors = [{name = "Eric", email = "bookdone.tech@outlook.com"}]
dynamic = ["version", "description"]
